version: "3"

services:
    backend:
        image: metakgp/gyfe
        container_name: gyfe
        build: .
        restart: always
        ports:
            - 8000:8000
        networks:
            metaploy-network:
                aliases:
                    - gyfe
        volumes:
            - nginx-config-volume:/etc/nginx/sites-enabled

networks:
    metaploy-network:
        external: true
        name: metaploy-network

volumes:
    nginx-config-volume:
        external: true
        name: metaploy-nginx-config-volume
